# Generated by Django 2.2.7 on 2019-12-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.CharField(max_length=200)),
                ('fullName', models.CharField(max_length=200)),
                ('PhoneCode', models.CharField(max_length=200)),
                ('PostalCode', models.CharField(max_length=200)),
                ('isActive', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacttype_id', models.CharField(max_length=200)),
                ('salutation', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=200)),
                ('middleName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('mobileNumber', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('isActive', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContactTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=200)),
                ('isActive', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_id', models.CharField(max_length=200)),
                ('fullName', models.CharField(max_length=200)),
                ('ISO', models.CharField(max_length=200)),
                ('PhoneCode', models.CharField(max_length=200)),
                ('isActive', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200)),
                ('Sign', models.CharField(max_length=200)),
                ('isActive', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LocalAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.CharField(max_length=200)),
                ('fullAddress', models.CharField(max_length=200)),
                ('isActive', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('auth_token', models.CharField(max_length=200)),
                ('token_expiry', models.CharField(max_length=200)),
                ('isActive', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SystemPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissionName', models.CharField(max_length=200)),
                ('moduleName', models.CharField(max_length=200)),
                ('isActive', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userRole_id', models.CharField(max_length=200)),
                ('systemPermission_id', models.CharField(max_length=200)),
                ('isActive', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200)),
                ('isActive', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('unq_id', models.CharField(max_length=255)),
                ('contact_id', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('emailAddr', models.CharField(max_length=200)),
                ('userRole_id', models.CharField(max_length=200)),
                ('isActive', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
    ]
